export const GET_LISTGAMES_BEGIN = "GET_LISTGAMES_BEGIN";
export const GET_LISTGAMES_SUCCESS = "GET_LISTGAMES_SUCCESS";
export const GET_LISTGAMES_ERROR = "GET_LISTGAMES_ERROR";
export const GET_SINGLE_GAME_BEGIN = "GET_SINGLE_GAME_BEGIN";
export const GET_SINGLE_GAME_SUCCESS = "GET_SINGLE_GAME_SUCCESS";
export const GET_SINGLE_GAME_ERROR = "GET_SINGLE_GAME_ERROR";
